//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalProject_V1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tOrder
    {
        public int fId { get; set; }

        public string fUserId { get; set; }

        public string fPdName { get; set; }

        public string fPdImage { get; set; }


        public int fPdPrice { get; set; }


        public string fPdDescription { get; set; }


        public int fBuyQuantity { get; set; }

        public string fUserName { get; set; }


        public string fUserPhone { get; set; }

        public string fUserAddress { get; set; }


        public string fUserPayway { get; set; }
    }
}
