//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalProject_V1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tProducts
    {
        [Display(Name = "序號")]
        public int fId { get; set; }

        [Required]
        [Display(Name = "商品名稱")]
        public string fName { get; set; }

        public string fImage { get; set; }

        [Required]
        [Display(Name = "價錢")]
        [Range(1, 9999, ErrorMessage = "請輸入大於1的數字")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "請輸入數字")]
        public int fPrice { get; set; }

        [Required]
        [Display(Name = "描述")]
        public string fDescription { get; set; }

        [Required]
        [Range(1,9999, ErrorMessage ="請輸入大於1的數字")]
        [RegularExpression(@"^[0-9]*$", ErrorMessage = "請輸入數字")]
        [Display(Name = "數量")]
        public int fQuantity { get; set; }
    }
}
